export function exportReport({ code, language, score, issues = [], model = 'auto', timestamp }) {
  const scoreColor = score >= 86 ? '#6366f1' : score >= 66 ? '#22c55e' : score >= 41 ? '#f59e0b' : '#ef4444';
  const scoreLabel = score >= 86 ? 'Excellent' : score >= 66 ? 'Good' : score >= 41 ? 'Fair' : 'Needs Work';

  const issueRows = issues.map(issue => `
    <div class="issue ${(issue.severity || 'info').toLowerCase()}">
      <div class="issue-header">
        <span class="badge ${(issue.severity || 'info').toLowerCase()}">${issue.severity || 'INFO'}</span>
        <strong>${issue.title || issue.message || 'Issue'}</strong>
        ${issue.line ? `<span class="line">Line ${issue.line}</span>` : ''}
      </div>
      ${issue.description ? `<p>${issue.description}</p>` : ''}
      ${issue.fix ? `<div class="fix"><strong>Suggested fix:</strong> ${issue.fix}</div>` : ''}
    </div>`).join('');

  const safeCode = (code || '').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');

  const html = `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Refyn Report — ${new Date(timestamp || Date.now()).toLocaleDateString()}</title>
  <style>
    * { margin:0; padding:0; box-sizing:border-box; }
    body { font-family:-apple-system,BlinkMacSystemFont,'Inter',sans-serif; color:#111; padding:40px; max-width:820px; margin:0 auto; }
    h1 { font-size:24px; font-weight:700; margin-bottom:4px; }
    .meta { color:#666; font-size:13px; margin-bottom:28px; }
    .logo { color:#6366f1; margin-right:4px; }

    .score-block {
      display:flex; align-items:center; gap:24px;
      padding:20px 24px; border:1px solid #e5e5e5; border-radius:10px; margin-bottom:28px;
    }
    .score-num { font-size:56px; font-weight:700; color:${scoreColor}; line-height:1; }
    .score-meta .label { font-size:18px; font-weight:600; color:${scoreColor}; }
    .score-meta .sub { font-size:12px; color:#888; margin-top:3px; }

    h2 { font-size:15px; font-weight:700; margin-bottom:12px; padding-bottom:8px; border-bottom:2px solid #f0f0f0; }
    section { margin-bottom:28px; }

    .issue { padding:14px 16px; margin-bottom:10px; border-left:4px solid; border-radius:0 7px 7px 0; background:#fafafa; }
    .issue.critical { border-color:#ef4444; }
    .issue.warning  { border-color:#f59e0b; }
    .issue.info     { border-color:#6366f1; }
    .issue-header { display:flex; align-items:center; gap:8px; margin-bottom:6px; }
    .badge { padding:2px 7px; border-radius:4px; font-size:10px; font-weight:700; color:white; text-transform:uppercase; }
    .badge.critical { background:#ef4444; }
    .badge.warning  { background:#f59e0b; }
    .badge.info     { background:#6366f1; }
    .line { font-size:11px; color:#999; margin-left:auto; }
    p { font-size:13px; color:#444; line-height:1.55; margin-top:4px; }
    .fix { margin-top:8px; padding:8px 12px; background:#f0fdf4; border-radius:5px; font-size:12px; color:#15803d; }

    .code-block { background:#1a1a24; border-radius:8px; padding:20px; }
    .code-block h2 { color:#f1f1f5; border-color:#2a2a3a; }
    pre { font-family:'JetBrains Mono','Courier New',monospace; font-size:12px; color:#a0a0b0; line-height:1.65; white-space:pre-wrap; word-break:break-all; }

    .footer { margin-top:32px; padding-top:16px; border-top:1px solid #eee; text-align:center; color:#aaa; font-size:11px; }

    @media print {
      body { padding:20px; }
      .code-block { -webkit-print-color-adjust:exact; print-color-adjust:exact; }
    }
  </style>
</head>
<body>
  <h1><span class="logo">⬡</span> Refyn Analysis Report</h1>
  <p class="meta">
    ${language || 'Unknown language'} &nbsp;·&nbsp;
    ${new Date(timestamp || Date.now()).toLocaleString()} &nbsp;·&nbsp;
    Model: ${model}
  </p>

  <div class="score-block">
    <div class="score-num">${score ?? '—'}</div>
    <div class="score-meta">
      <div class="label">${scoreLabel}</div>
      <div class="sub">out of 100 &nbsp;·&nbsp; ${issues.length} issue${issues.length !== 1 ? 's' : ''} found</div>
    </div>
  </div>

  <section>
    <h2>Issues Found</h2>
    ${issueRows || '<p style="color:#888;padding:8px 0">No issues detected.</p>'}
  </section>

  <section class="code-block">
    <h2>Analyzed Code</h2>
    <pre>${safeCode}</pre>
  </section>

  <div class="footer">
    Generated by Refyn &nbsp;·&nbsp; AI Code Intelligence Workspace
  </div>
</body>
</html>`;

  const blob = new Blob([html], { type: 'text/html' });
  const url = URL.createObjectURL(blob);
  const win = window.open(url, '_blank');
  if (win) {
    setTimeout(() => {
      win.print();
      setTimeout(() => URL.revokeObjectURL(url), 60000);
    }, 700);
  }
}
